### ISSUE TITLE
add `tic` as an option for templating travis.yml files

### ISSUE THREAD

**Issue by yonicd** [yonicd/covrpage#28]
add to [use_covrpage](https://github.com/yonicd/covrpage/blob/master/R/use_covrpage.R#L29) and option to build a tic.R file and a travis.yml that has `tic` dependency.

**Comment by maelle** [comment]
it would be more than that, I'm wondering whether it could "just" take over the current `use_covrpage()`, because `travis::use_tic()` also helps with:
* getting deploy tokens
* getting a `GITHUB_PAT` just for Travis

So there could be
* a wrapper of that, more or less, using a tic.R that contains the call to `covrpage`.
* in the docs a link to that tic.R in case a developer already has a tic.R that just needs updating with the `covrpage` command.

**Comment by yonicd** [comment]
`GITHUB_PAT` is great for `GITHUB` repos, but users are also using `GHE`, which needs a different `PAT`, how does tic handle that?

**Comment by maelle** [comment]
@krlmlr does `tic` handle GitHub Enterprise? I don't think so?

**Comment by krlmlr** [comment]
I have never tried. But since _tic_ can execute arbitrary R code, I'm confident a solution can be worked out with `add_code_step()`, and maybe later integrated if necessary.

**Comment by yonicd** [comment]
does tic have a way to encrypt a local environmental variable for appveyor? the ghe token is different than the gh token.

**Comment by krlmlr** [comment]
Have you seen https://www.appveyor.com/docs/build-configuration/#secure-variables? Currently we don't have a way to do this automatically.

**Comment by maelle** [comment]
What I did to get `covrpage` README and vignette deploying for `pRojects` (not fully there yet...)
* Added `covrpage` to Suggests and Remotes. When/if `covrpage` gets to CRAN, only Suggests will be needed.
* Added these lines to the tic.R
```r
get_stage("after_success") %>%
  add_code_step(covr::codecov()) %>%
  add_code_step(devtools::install()) %>%
  add_code_step(covrpage::covrpage_ci())
```
(`covrpage` needs the package to be installed)

and 
```
  if (ci()$get_branch() == "master") {
  get_stage("deploy") %>%
    add_step(step_push_deploy(commit_paths = "tests/README.md")) %>%
    add_step(step_build_pkgdown()) %>%
    add_step(step_push_deploy(path = "docs", branch = "gh-pages"))
  }else{
    get_stage("deploy") %>%
      add_step(step_push_deploy(commit_paths = "tests/README.md"))

  }
```

instead of just the `pkgdown` usual stuff. It doesn't work yet because "tests/README.md" is staged, there's nothing to commit, then there's a message saying it was modified but not staged. I'm a bit lost at the moment.

**Comment by maelle** [comment]
I'm not sure how this should be documented in `covrpage` when it works.
* just with words, pointing at an example tic.R
* covrpage having its own `use_tic()` wrapper with its own tic.R but hard to keep that updated.

**Comment by maelle** [comment]
Now it works see https://github.com/lockedata/pRojects/blob/master/tic.R

**Comment by yonicd** [comment]
I tried to set it up using this [branch](https://github.com/yonicd/covrpage/tree/tic). I am still confused on how to use tic. Currently it is still not deploying.

**Comment by maelle** [comment]
is it deploying now?

and if it is, what's your view now on a re-factoring of `use_covrpage`?

**Comment by yonicd** [comment]
It is deploying now. I think that I'll keep it as an option and not as the default. so users can choose their comfort zone yml/tic/bash

**Comment by maelle** [comment]
I'll let you handle this, then? Seems easier given how well you know `use_covrpage()` 😉

**Comment by maelle** [comment]
It looks good!

**Comment by yonicd** [comment]
https://github.com/yonicd/covrpage/commit/2c97fc10e128282a23292e47ff4be29a6c2fc818
